# Generated by Django 3.2.23 on 2024-04-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240102_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
