# Generated by Django 3.2.23 on 2024-05-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_expense_purchase_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='purchase_type',
            new_name='expense_type',
        ),
    ]
