# Generated by Django 3.2.23 on 2024-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remain_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
