# Generated by Django 3.2.23 on 2024-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_recentaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentaction',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
